/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    FlightBooking: {
      address: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "_owner",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "Deposit",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "flightId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "fromAirport",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "toAirport",
              type: "string",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "departureTime",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "arrivalTime",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "availableTickets",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "pricePerTicket",
              type: "uint256",
            },
          ],
          name: "FlightAdded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "flightId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "ticketsCount",
              type: "uint256",
            },
          ],
          name: "FlightBooked",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "Withdrawal",
          type: "event",
        },
        {
          inputs: [],
          name: "DECIMALS",
          outputs: [
            {
              internalType: "uint8",
              name: "",
              type: "uint8",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "SCALING_FACTOR",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_fromAirport",
              type: "string",
            },
            {
              internalType: "string",
              name: "_toAirport",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "_departureTime",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_arrivalTime",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_availableTickets",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_pricePerTicket",
              type: "uint256",
            },
          ],
          name: "addFlight",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_flightId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_ticketsCount",
              type: "uint256",
            },
          ],
          name: "bookFlight",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "bookings",
          outputs: [
            {
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "flightId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "ticketsCount",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "flightCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "flights",
          outputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "fromAirport",
              type: "string",
            },
            {
              internalType: "string",
              name: "toAirport",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "departureTime",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "arrivalTime",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "availableTickets",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "pricePerTicket",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getAllFlights",
          outputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "id",
                  type: "uint256",
                },
                {
                  internalType: "string",
                  name: "fromAirport",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "toAirport",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "departureTime",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "arrivalTime",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "availableTickets",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "pricePerTicket",
                  type: "uint256",
                },
              ],
              internalType: "struct FlightBooking.Flight[]",
              name: "",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_fromAirport",
              type: "string",
            },
            {
              internalType: "string",
              name: "_toAirport",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "_startTime",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_endTime",
              type: "uint256",
            },
          ],
          name: "getAvailableFlights",
          outputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "id",
                  type: "uint256",
                },
                {
                  internalType: "string",
                  name: "fromAirport",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "toAirport",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "departureTime",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "arrivalTime",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "availableTickets",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "pricePerTicket",
                  type: "uint256",
                },
              ],
              internalType: "struct FlightBooking.Flight[]",
              name: "",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_flightId",
              type: "uint256",
            },
          ],
          name: "getFlight",
          outputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "fromAirport",
              type: "string",
            },
            {
              internalType: "string",
              name: "toAirport",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "departureTime",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "arrivalTime",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "availableTickets",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "index",
              type: "uint256",
            },
          ],
          name: "getMyBooking",
          outputs: [
            {
              internalType: "uint256",
              name: "flightId",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "fromAirport",
              type: "string",
            },
            {
              internalType: "string",
              name: "toAirport",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "departureTime",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "arrivalTime",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "ticketsCount",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getMyBookingCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
